databases:
  - name: mysitedb
    plan: free
    connectionString: "mongodb://tsedey:EjOiKLdQngoIwhdB@attendance.upm826h.mongodb.net/Attendance_V2?retryWrites=true&w=majority"

services:
  - type: web
    plan: free
    name: backendattendance
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn BackendAttendance.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DB_NAME
        value: "Attendance_V2"
      - key: DB_CONNECTION_STRING
        value: "mongodb://tsedey:EjOiKLdQngoIwhdB@attendance.upm826h.mongodb.net/Attendance_V2?retryWrites=true&w=majority"
