databases:
  - name: mysitedb
    plan: free
    databaseName: Attendance_V2
    user: tsedey
    properties:
      - key: password
        value: EjOiKLdQngoIwhdB
      - key: host
        value: attendance.upm826h.mongodb.net
      - key: port
        value: 27017

services:
  - type: web
    plan: free
    name: backendattendance
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn BackendAttendance.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DB_NAME
        value: "Attendance_V2"
      - key: DB_HOST
        value: "attendance.upm826h.mongodb.net"
      - key: DB_PORT
        value: "27017"
      - key: DB_USERNAME
        value: "tsedey"
      - key: DB_PASSWORD
        value: "EjOiKLdQngoIwhdB"
