# Generated by Django 4.1.13 on 2024-05-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='college',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
