# Generated by Django 4.1.13 on 2024-05-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0003_rename_user_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('evidence', models.FileField(upload_to='evidence/')),
                ('sick_leave', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='course',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='college',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
